name: Docker Build

on:
  schedule:
    - cron: "0 7 * * 1"
  push:
    branches: master

jobs:
  build:
    name: Build PHP ${{ matrix.php_version }} Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["5.6", "7.0", "7.1",  "7.2", "7.3", "7.4"]
        include:
          - php_version: "7.4"
            extra_tags: ",clevyr/php:latest,clevyr/laravel-base-image-builder:latest"
    steps:
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: clevyr/php:${{ matrix.php_version }},clevyr/laravel-base-image-builder:${{ matrix.php_version }}${{ matrix.extra_tags }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}

  readme:
    name: Update DockerHub Description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: clevyr/php

      - uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: clevyr/laravel-base-image-builder
