name: Docker Build

on:
  schedule:
    - cron: "0 7 * * 1"
  push:
    branches: master

jobs:
  build:
    name: Build PHP ${{ matrix.php_version }} Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.1",  "7.2", "7.3", "7.4", "8.0"]
        platforms: ["linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x"]
        include:
          - php_version: "5.6"
            platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm64/v8,linux/ppc64le
            extra_tags: |
              clevyr/php:5
          - php_version: "7.0"
            platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm64/v8,linux/ppc64le
          - php_version: "7.4"
            extra_tags: |
              clevyr/php:7
          - php_version: "8.0"
            extra_tags: |
              clevyr/php:latest
              clevyr/php:8
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.php_version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.php_version }}
            ${{ runner.os }}-buildx-

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          pull: true
          push: true
          platforms: ${{ matrix.platforms }}
          tags: |
            clevyr/php:${{ matrix.php_version }}
            ${{ matrix.extra_tags }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: Move Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  readme:
    name: Update DockerHub Description
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: clevyr/php
